name: Deploy to staging
on:
  push:
    branches: [main]

  jobs:
    deploy:
      name: Push to EC2
      runs-on: ubuntu-latest

      steps:
        - name: checkout the code
          uses: actions/checkout@v2

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: 13.126.205.19
            username: ubuntu
            key: "${{ secrets.SSH_PRIVATE_KEY }}"
            port: 22
            script: ./deploy.sh
